export const ADD_BASKET = 'ADD_BASKET';
export const REMOVE_BASKET = "REMOVE_BASKET";
export const CLEAR_BASKET = "CLEAR_BASKET";
export const GET_BASKET = "GET_BASKET";
export const INCREASE_QUANTITY = "INCREASE_QUANTITY"
export const DECREASE_QUANTITY = "DECREASE_QUANTITY"

